cmake -S . -B build \
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_INSTALL_PREFIX=../install \
-DCMAKE_BUILD_TYPE=Release \
-DHEXL_SHARED_LIB=OFF \
-DHEXL_EXPERIMENTAL=ON \
-DHEXL_BENCHMARK=OFF \
-DHEXL_TESTING=OFF \
-DHEXL_FPGA=ON

cmake --build build -j
